// SPDX-FileCopyrightText: 2026 Kevin Monaghan
// SPDX-License-Identifier: MIT-0

use crate::Error;
use serde::{Deserialize, Serialize};
/// Caller-owned withdrawal reconciliation identity; never generated by the client.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct WithdrawalId(String);
impl WithdrawalId {
    /// Retain a nonempty provider identity without transforming it.
    ///
    /// # Errors
    /// Refuses empty strings and control characters.
    pub fn new(value: impl Into<String>) -> Result<Self, Error> {
        let value = value.into();
        if value.is_empty() || value.chars().any(char::is_control) {
            return Err(Error::Validation("withdrawal identity"));
        }
        Ok(Self(value))
    }
    /// The exact caller identity.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
impl<'de> Deserialize<'de> for WithdrawalId {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        Self::new(String::deserialize(d)?).map_err(serde::de::Error::custom)
    }
}

/// Nonempty caller-selected dust assets, encoded as Binance's comma-separated list.
#[derive(Clone, Debug)]
pub struct DustAssets(Vec<crate::Asset>);
impl DustAssets {
    /// Preserve asset identities without choosing or combining their balances.
    ///
    /// # Errors
    /// Refuses empty lists, duplicate assets and identities containing a comma.
    pub fn new(assets: Vec<crate::Asset>) -> Result<Self, Error> {
        let mut seen = std::collections::BTreeSet::new();
        if assets.is_empty()
            || assets
                .iter()
                .any(|a| a.as_str().contains(',') || !seen.insert(a.as_str()))
        {
            return Err(Error::Validation("dust asset list"));
        }
        Ok(Self(assets))
    }
    /// The original caller-selected assets.
    #[must_use]
    pub fn assets(&self) -> &[crate::Asset] {
        &self.0
    }
}
impl Serialize for DustAssets {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(
            &self
                .0
                .iter()
                .map(crate::Asset::as_str)
                .collect::<Vec<_>>()
                .join(","),
        )
    }
}
